package com.demo.entities;
// Generated Mar 20, 2024, 12:49:52 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.hibernate.annotations.Parent;
import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

import jakarta.persistence.*;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "account")
public class Account implements java.io.Serializable {

	private Integer id;
	private Role role;
	private String username;
	private String password;
	private String fullname;
	private String email;
	private boolean gender;
	private String address;
	private String photo;
	private String phone;
	@JsonFormat(pattern = "dd/MM/yyyy")
	private Date dob;
	private boolean status;
	private String securityCode;
	private Set<Input> inputs = new HashSet<Input>(0);
	private Set<Output> outputs = new HashSet<Output>(0);

	public Account() {
	}
	
	public Account(int id) {
		this.id = id;
	}

	public Account(Role role, String username, String password, String fullname, String email, boolean gender,
			String address, String photo, String phone, Date dob, boolean status, String securityCode) {
		this.role = role;
		this.username = username;
		this.password = password;
		this.fullname = fullname;
		this.email = email;
		this.gender = gender;
		this.address = address;
		this.photo = photo;
		this.phone = phone;
		this.dob = dob;
		this.status = status;
		this.securityCode = securityCode;
	}

	public Account(Role role, String username, String password, String fullname, String email, boolean gender,
			String address, String photo, String phone, Date dob, boolean status, String securityCode,
			Set<Input> inputs, Set<Output> outputs) {
		this.role = role;
		this.username = username;
		this.password = password;
		this.fullname = fullname;
		this.email = email;
		this.gender = gender;
		this.address = address;
		this.photo = photo;
		this.phone = phone;
		this.dob = dob;
		this.status = status;
		this.securityCode = securityCode;
		this.inputs = inputs;
		this.outputs = outputs;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id", nullable = false)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@Column(name = "username", nullable = false)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "fullname", nullable = false)
	public String getFullname() {
		return this.fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	@Column(name = "email", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "gender", nullable = false)
	public boolean getGender() {
		return this.gender;
	}

	public void setGender(boolean gender) {
		this.gender = gender;
	}

	@Column(name = "address", nullable = false)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "photo", nullable = false)
	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	@Column(name = "phone", nullable = false)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dob", nullable = false, length = 10)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Column(name = "security_code", nullable = false, length = 250)
	public String getSecurityCode() {
		return this.securityCode;
	}

	public void setSecurityCode(String securityCode) {
		this.securityCode = securityCode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Input> getInputs() {
		return this.inputs;
	}

	public void setInputs(Set<Input> inputs) {
		this.inputs = inputs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Output> getOutputs() {
		return this.outputs;
	}

	public void setOutputs(Set<Output> outputs) {
		this.outputs = outputs;
	}

}
