package com.demo.entities;
// Generated Mar 19, 2024, 10:32:58 PM by Hibernate Tools 4.3.6.Final

import java.time.LocalDateTime;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.springframework.format.annotation.DateTimeFormat;

import jakarta.persistence.*;

/**
 * Input generated by hbm2java
 */
@Entity
@Table(name = "input")
public class Input implements java.io.Serializable {

	private Integer id;
	private Account account;
	private Suplier suplier;
	@DateTimeFormat(pattern = "dd/MM/yyyy HH:mm:ss")
	private LocalDateTime date;
	private String inputinfo;
	private String status;
	private Set<Inputifo> inputifos = new HashSet<Inputifo>(0);

	public Input() {
	}

	public Input(Account account, Suplier suplier, LocalDateTime date, String inputinfo, String status) {
		this.account = account;
		this.suplier = suplier;
		this.date = date;
		this.inputinfo = inputinfo;
		this.status = status;
	}

	public Input(Account account, Suplier suplier, LocalDateTime date, String inputinfo, String status,
			Set<Inputifo> inputifos) {
		this.account = account;
		this.suplier = suplier;
		this.date = date;
		this.inputinfo = inputinfo;
		this.status = status;
		this.inputifos = inputifos;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_id", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "suplier_id", nullable = false)
	public Suplier getSuplier() {
		return this.suplier;
	}

	public void setSuplier(Suplier suplier) {
		this.suplier = suplier;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", nullable = false, length = 19)
	public LocalDateTime getDate() {
		return this.date;
	}

	public void setDate(LocalDateTime date) {
		this.date = date;
	}

	@Column(name = "inputinfo", nullable = false, length = 16777215)
	public String getInputinfo() {
		return this.inputinfo;
	}

	public void setInputinfo(String inputinfo) {
		this.inputinfo = inputinfo;
	}

	@Column(name = "status", nullable = false, length = 250)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "input")
	public Set<Inputifo> getInputifos() {
		return this.inputifos;
	}

	public void setInputifos(Set<Inputifo> inputifos) {
		this.inputifos = inputifos;
	}

}
