package com.demo.entities;
// Generated Mar 19, 2024, 2:04:27 PM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.*;

/**
 * Inputifo generated by hbm2java
 */
@Entity
@Table(name = "inputifo")
public class Inputifo implements java.io.Serializable {

	private Integer id;
	private Input input;
	private int productId;
	private int count;

	public Inputifo() {
	}
	
	public Inputifo(int id) {
		this.id = id;
	}

	public Inputifo(Input input, int productId, int count) {
		this.input = input;
		this.productId = productId;
		this.count = count;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "input_id", nullable = false)
	public Input getInput() {
		return this.input;
	}

	public void setInput(Input input) {
		this.input = input;
	}

	@Column(name = "product_id", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	@Column(name = "count", nullable = false)
	public int getCount() {
		return this.count;
	}

	public void setCount(int count) {
		this.count = count;
	}

}
