package com.demo.entities;

import jakarta.persistence.*;

// Generated Mar 20, 2024, 1:38:17 PM by Hibernate Tools 4.3.6.Final



/**
 * Outputinfor generated by hbm2java
 */
@Entity
@Table(name = "outputinfor")
public class Outputinfor implements java.io.Serializable {

	private Integer id;
	private Output output;
	private Product product;
	private int count;
	private double price;

	public Outputinfor() {
	}

	public Outputinfor(Output output, Product product, int count, double price) {
		this.output = output;
		this.product = product;
		this.count = count;
		this.price = price;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "output_id", nullable = false)
	public Output getOutput() {
		return this.output;
	}

	public void setOutput(Output output) {
		this.output = output;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "count", nullable = false)
	public int getCount() {
		return this.count;
	}

	public void setCount(int count) {
		this.count = count;
	}

	@Column(name = "price", nullable = false, precision = 22, scale = 0)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

}
