package com.demo.entities;
// Generated Mar 20, 2024, 12:49:52 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.*;
/**
 * Output generated by hbm2java
 */
@Entity
@Table(name = "output")
public class Output implements java.io.Serializable {

	private Integer id;
	private Account account;
	private Customer customer;
	private Date date;
	private String status;
	private Set<Outputinfor> outputinfors = new HashSet<Outputinfor>(0);

	public Output() {
	}

	public Output(Customer customer, Date date, String status) {
		this.customer = customer;
		this.date = date;
		this.status = status;
	}

	public Output(Account account, Customer customer, Date date, String status, Set<Outputinfor> outputinfors) {
		this.account = account;
		this.customer = customer;
		this.date = date;
		this.status = status;
		this.outputinfors = outputinfors;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_id")
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", nullable = false, length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "status", nullable = false, length = 250)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "output")
	public Set<Outputinfor> getOutputinfors() {
		return this.outputinfors;
	}

	public void setOutputinfors(Set<Outputinfor> outputinfors) {
		this.outputinfors = outputinfors;
	}

}
