package com.demo.entities;
// Generated Mar 19, 2024, 2:04:27 PM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.*;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product")
public class Product implements java.io.Serializable {

	private Integer id;
	private Category category;
	private Suplier suplier;
	private String name;
	private double price;
	private int quantity;
	private int minimumquantity;
	private int profit;
	private String description;
	private String status;
	private String picture;

	public Product() {
	}

	public Product(int id) {
		this.id = id;
	}
	
	public Product(Category category, Suplier suplier, String name, double price, int quantity, int minimumquantity,
			int profit, String description, String status, String picture) {
		this.category = category;
		this.suplier = suplier;
		this.name = name;
		this.price = price;
		this.quantity = quantity;
		this.minimumquantity = minimumquantity;
		this.profit = profit;
		this.description = description;
		this.status = status;
		this.picture = picture;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id", nullable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "suplier_id", nullable = false)
	public Suplier getSuplier() {
		return this.suplier;
	}

	public void setSuplier(Suplier suplier) {
		this.suplier = suplier;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "price", nullable = false, precision = 22, scale = 0)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "minimumquantity", nullable = false)
	public int getMinimumquantity() {
		return this.minimumquantity;
	}

	public void setMinimumquantity(int minimumquantity) {
		this.minimumquantity = minimumquantity;
	}

	@Column(name = "profit", nullable = false)
	public int getProfit() {
		return this.profit;
	}

	public void setProfit(int profit) {
		this.profit = profit;
	}

	@Column(name = "description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "status", nullable = false)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "picture", nullable = false, length = 250)
	public String getPicture() {
		return this.picture;
	}

	public void setPicture(String picture) {
		this.picture = picture;
	}

}
